name: forsan
description: A Printing Service APP.

version: 1.0.2+15

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  hexcolor: ^3.0.1
#  cloud_firestore: ^4.8.4
#  firebase_auth: ^4.7.2
#  firebase_core: ^2.15.0
#  firebase_core: ^2.25.4
  cloud_functions: ^4.6.0
  firebase_auth: ^4.17.5
  cloud_firestore: ^4.15.5
  firebase_storage: ^11.2.6

  flutter_bloc: ^8.1.3
  google_fonts: ^4.0.4
#  firebase_storage: ^11.2.5
  loading_animation_widget: ^1.2.0+4
  animated_bottom_navigation_bar: ^1.2.0
#  awesome_snackbar_content: ^0.1.3
  flutter_icon_snackbar: ^1.1.4
  shared_preferences: ^2.2.0
  file_picker: ^5.3.3
  introduction_screen: ^3.1.11
  url_launcher: ^6.1.12
  dart_secure: 0.5.25
  image_picker: ^1.0.4
  moyasar: ^2.0.2
  cached_network_image: ^3.4.0
  firebase_core: ^2.31.0
#  cached_network_image_web: ^1.3.1 # Replace with a compatible version if available

dev_dependencies:
  device_preview: ^1.1.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.12.0"
  flutter_lints: ^2.0.2


flutter_icons:
  android: true
  ios: true
  image_path: "assets/forsan_logo.jpeg"

flutter:
  uses-material-design: true

  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Regular.ttf
        #        - asset: assets/fonts/Almarai-Italic.ttf
        #          style: italic
        - asset: assets/fonts/Almarai-Light.ttf
          weight: 200
        - asset: assets/fonts/Almarai-Bold.ttf
          weight: 700
        - asset: assets/fonts/Almarai-ExtraBold.ttf
          weight: 900

  assets:
    - assets/forsan_logo.jpeg
    - assets/forsan_no_bg.png
    - assets/homebg.jpg
    - assets/print.gif
    - assets/printingGif.gif
    - assets/profilePicture.jpg
    - shorebird.yaml